spring.application.name=Cefla-talent


# Server configuration
server.port=8080
server.address=0.0.0.0

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/test
spring.datasource.username=
spring.datasource.password=

# Hibernate configuration
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
logging.level.org.hibernate.SQL=DEBUG

# Logging configuration
#logging.level.org.springframework=INFO
logging.level.org.springframework.security=DEBUG
logging.level.io.jsonwebtoken=DEBUG